### ISSUE TITLE
what do i do :/

### ISSUE THREAD

**Issue by mypasswordis12345lol** [flarfo/SBM-Custom-Levels#1]
idk it just wont let me extract to a specific spot so i just pasted the folders in my directory and nothing happens bruh

**Comment by flarfo** [comment]
Make sure your folder looks exactly this (the changelog file DOES NOT matter):
https://github.com/flarfo/SBM-Custom-Levels/blob/master/icon/install-step5.png

If that doesn't work, you can join the discord and I can try helping you there. I will make a video install guide soon so its easier to follow, and will try to fix any problems.
